version: '3.4'

services:
  webcalcexpressmongoapi:
    image: webcalcexpressmongoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  mongo:
    image: mongo
    ports: [ '27017:27017' ]
